### ISSUE TITLE
Team members section broken

### ISSUE THREAD

**Issue by bartekrutkowski** [digitalcraftsman/hugo-agency-theme#36] opened 2016-10-20 19:10 UTC
Whenever the teams member number is not 3, 6, 9... the team members section keeps the members aligned to the left, leaving gaps or free space on the right side, instead of centering them.

**Comment by digitalcraftsman** [comment] 2016-10-22 15:14
Hello @bartekrutkowski,

the original theme author did this by design. Each team member and it's information are part of a container. All containers have a with of ca. 33%. If a container doesn't fit in a row anymore it moves in a new line which have a left alignment by default.

**Comment by stp-ip** [comment] 2016-11-11 19:05
Wasn't autoclosed, but is also fixed with #44

**Closed as completed** 2016-11-11 19:08 UTC

**Comment by stp-ip** [comment] 2016-11-11 19:19
With #45 the changes as default is removed, but you can easily add "center = true" to enable centering of items, if that fits your design goals better.
